[IM]
overlay=libmb.so mb/sbltdz.txt
cand=6
lang=0
skin=skin 1
auto_move=0
ABCD=0
onspot=1

[input]
#select=\s2. 3. 7. 8. 9.

[key]
#select=a e u i o
select_n=\s23789
CNen=SHIFT
page=SHIFT_TAB TAB

[table]
zi_mode=1
